/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WtfSHero {
        /**
          * The description
         */
        "description": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWtfSHeroElement extends Components.WtfSHero, HTMLStencilElement {
    }
    var HTMLWtfSHeroElement: {
        prototype: HTMLWtfSHeroElement;
        new (): HTMLWtfSHeroElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "wtf-s-hero": HTMLWtfSHeroElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WtfSHero {
        /**
          * The description
         */
        "description"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "wtf-s-hero": WtfSHero;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wtf-s-hero": LocalJSX.WtfSHero & JSXBase.HTMLAttributes<HTMLWtfSHeroElement>;
        }
    }
}
